# Build documentation in the latest version of Sphinx
version: 2

# Use the Python version specified in your project
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  commands:
    - pip install poetry
    # Tell poetry to not use a virtual environment
    - poetry config virtualenvs.create false
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
    - sphinx-build -b html docs/source docs/build
    - cp -r docs/build/html $READTHEDOCS_PROJECT_PATH/html
