# Build documentation in the latest version of Sphinx
version: 2

# Use the Python version specified in your project
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --only docs

  commands:
    - cd docs
    - chmod +x make.sh
    - ./make.sh html
    - cp -r build/html $READTHEDOCS_PROJECT_PATH/html

# Specify the Sphinx version
sphinx:
  configuration: docs/source/conf.py
  builder: html
