# Build documentation in the latest version of Sphinx
version: 2

# Use the Python version specified in your project
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

  jobs:
    post_create_environment:
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
      - poetry install --only docs

# Specify the Sphinx version
sphinx:
  configuration: docs/source/conf.py
  builder: html
